from __future__ import annotations
from typing import Any,Protocol

class ReferenceGateway(Protocol):
    def health(self)->dict[str,Any]: ...
    def upsert_campaign(self,payload:dict[str,Any])->dict[str,Any]: ...
    def register_message(self,payload:dict[str,Any])->dict[str,Any]: ...
    def enroll(self,campaign_rcvo_id:str,limit:int)->dict[str,Any]: ...
    def claim(self,campaign_rcvo_id:str,worker_id:str,limit:int,lease_seconds:int)->list[dict[str,Any]]: ...
    def release(self,campaign_contact_id:int,worker_id:str,*,next_eligible_at:str|None=None,error:bool=False)->None: ...
    def events(self,events:list[dict[str,Any]])->dict[str,Any]: ...
    def suppress(self,payload:dict[str,Any])->dict[str,Any]: ...

class MailTransport(Protocol):
    def send(self,message,mailbox:dict[str,Any])->dict[str,Any]: ...
