name: Cost Optimize (lecture seule)

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Exécuter des actions destructives ? (false = lecture seule)"
        required: true
        default: "false"
  schedule:
    - cron: "15 4 * * *"  # tous les jours à 04:15 UTC

permissions:
  id-token: write
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-3

      - name: Cost Explorer – récap 7 jours
        run: |
          aws ce get-cost-and-usage \
            --time-period Start=$(date -u -d '7 days ago' +%F),End=$(date -u +%F) \
            --granularity DAILY \
            --metrics "UnblendedCost" \
            --query 'ResultsByTime[].{Date:TimePeriod.Start,USD:Total.UnblendedCost.Amount}' \
            --output table

      - name: Compute Optimizer – résumé
        run: |
          aws compute-optimizer get-recommendation-summaries --output table
