name: Debug EB

on: { workflow_dispatch: {} }

permissions: { id-token: write, contents: read }
env: { AWS_REGION: eu-west-3 }

jobs:
  dbg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          aws elasticbeanstalk describe-environments \
            --query 'Environments[*].[ApplicationName,EnvironmentName,Status,Health]' \
            --output table --region eu-west-3
