name: Deploy Backend (OIDC)

on:
  push:
    branches: [ main, staging, dev ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGION: eu-west-3
  APP_NAME: Rcvo-backend
  ENV_STAGING: Rcvo-Backend-staging
  ENV_PROD: Rcvo-Backend-prod
  # Renseigne (optionnel) tes vrais hosts si tu veux éviter -k pendant le smoke test
  SMOKE_HOST_STAGING: ""   # ex: api-transition.rcvo.fr
  SMOKE_HOST_PROD: ""      # ex: api.rcvo.fr

jobs:
  deploy:
    runs-on: ubuntu-latest
