name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::409818814260:role/GithubOIDCRcvoDeploy
          aws-region: eu-west-3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli zip

      - name: Zip application
        run: |
          zip -r app.zip . -x "*.git*"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Rcvo-backend \
            --version-label "build-${GITHUB_SHA}" \
            --source-bundle S3Bucket="rcvo-officiel",S3Key="build-${GITHUB_SHA}.zip"

          aws s3 cp app.zip s3://rcvo-officiel/build-${GITHUB_SHA}.zip

          aws elasticbeanstalk update-environment \
            --environment-name rcvo-backend-prod \
            --version-label "build-${GITHUB_SHA}"
