name: Déploiement sur Elastic Beanstalk (OIDC)

on:
  push:
    branches:
      - main # Modifie la branche selon ton besoin

permissions:
  id-token: write # Nécessaire pour OIDC avec AWS
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<RoleName> # Remplace avec ton ARN
          aws-region: eu-west-1 # Modifie la région si besoin

      - name: Déployer sur Elastic Beanstalk
        run: |
          # Tes commandes de déploiement ici
