name: Rcvo – Déploiement en toute sécurité (projet racine)

on:
  push:
    branches: [ main, principal ]
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: Rcvo-backend
  STAGING_ENV: Rcvo-Backend-staging
  PROD_ENV: Rcvo-Backend-prod
  BUCKET: rcvo-officiel
  HEALTH_PATH: /health
  SYNC_HEALTH: /api/sync/health
  VERIFY_HEALTH: /api/verify/health
  ALLOWED_ORIGIN: https://www.rcvo-crm-auto.com
  LABEL: build-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with: { node-version: '22' }

      # Si pas de package-lock.json, npm ci échoue -> on bascule sur npm i
      - name: Install deps
        run: npm ci || npm i

      - name: Pack (sans node_modules et .git)
        run: zip -r app.zip . -x "node_modules/*" ".git/*"

      - name: Auth AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload vers S3
        run: aws s3 cp app.zip "s3://${{ env.BUCKET }}/${{ env.APP_NAME }}/${{ env.LABEL }}.zip"

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Auth AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Créer version EB + variables d'env (STAGING)
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ env.APP_NAME }}" \
            --version-label "${{ env.LABEL }}" \
            --source-bundle S3Bucket="${{ env.BUCKET }}",S3Key="${{ env.APP_NAME }}/${{ env.LABEL }}.zip" || true

          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.STAGING_ENV }}" \
            --option-settings \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=ALLOWED_ORIGIN,Value="${{ env.ALLOWED_ORIGIN }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=JWT_SECRET,Value="${{ secrets.RCVO_JWT_SECRET }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=ADMIN_EMAIL,Value="${{ secrets.RCVO_ADMIN_EMAIL }}" \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=ADMIN_PASSWORD,Value="${{ secrets.RCVO_ADMIN_PASSWORD }}"

          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.STAGING_ENV }}" \
            --version-label "${{ env.LABEL }}"

      - name: Attendre GREEN (STAGING)
        run: |
          for i in {1..40}; do
            H=$(aws elasticbeanstalk describe-environments --environment-names "${{ env.STAGING_ENV }}" --query "Environments[0].Health" --output text)
            S=$(aws elasticbeanstalk describe-environments --environment-names "${{ env.STAGING_ENV }}" --query "Environments[0].Status" --output text)
            echo "Health=$H Status=$S"
            [ "$H" = "Green" ] && [ "$S" = "Ready" ] && exit 0
            sleep 15
          done
          exit 1

      - name: Smoke tests (STAGING)
        run: |
          URL="https://$(aws elasticbeanstalk describe-environments --environment-names "${{ env.STAGING_ENV }}" --query "Environments[0].CNAME" --output text)"
          for p in "${{ env.HEALTH_PATH }}" "${{ env.SYNC_HEALTH }}" "${{ env.VERIFY_HEALTH }}"; do
            ok=0
            for i in {1..10}; do
              code=$(curl -sk -o /dev/null -w "%{http_code}" "${URL}${p}")
              echo "${p} -> ${code}"
              [ "$code" = "200" ] && ok=1 && break
              sleep 3
            done
            [ $ok -eq 1 ] || { echo "Smoke failed on ${p}"; exit 1; }
          done

  promote-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Auth AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Mémoriser version actuelle PROD
        id: prev
        run: |
          PREV=$(aws elasticbeanstalk describe-environments --environment-names "${{ env.PROD_ENV }}" --query "Environments[0].VersionLabel" --output text)
          echo "prev=${PREV}" >> $GITHUB_OUTPUT

      - name: Déployer en PROD
        run: aws elasticbeanstalk update-environment --environment-name "${{ env.PROD_ENV }}" --version-label "${{ env.LABEL }}"

      - name: Attendre GREEN (PROD)
        id: waitgreen
        continue-on-error: true
        run: |
          for i in {1..40}; do
            H=$(aws elasticbeanstalk describe-environments --environment-names "${{ env.PROD_ENV }}" --query "Environments[0].Health" --output text)
            S=$(aws elasticbeanstalk describe-environments --environment-names "${{ env.PROD_ENV }}" --query "Environments[0].Status" --output text)
            echo "Health=$H Status=$S"
            [ "$H" = "Green" ] && [ "$S" = "Ready" ] && exit 0
            sleep 15
          done
          exit 1

      - name: Post-checks (PROD)
        id: prodchecks
        continue-on-error: true
        run: |
          URL="https://$(aws elasticbeanstalk describe-environments --environment-names "${{ env.PROD_ENV }}" --query "Environments[0].CNAME" --output text)"
          for p in "${{ env.HEALTH_PATH }}" "${{ env.SYNC_HEALTH }}" "${{ env.VERIFY_HEALTH }}"; do
            ok=0
            for i in {1..10}; do
              code=$(curl -sk -o /dev/null -w "%{http_code}" "${URL}${p}")
              echo "${p} -> ${code}"
              [ "$code" = "200" ] && ok=1 && break
              sleep 3
            done
            [ $ok -eq 1 ] || { echo "PROD check failed on ${p}"; exit 1; }
          done

      - name: Auto-rollback si échec
        if: steps.waitgreen.outcome == 'failure' || steps.prodchecks.outcome == 'failure'
        run: |
          echo "Checks failed. Rolling back to ${{ steps.prev.outputs.prev }}"
          aws elasticbeanstalk update-environment --environment-name "${{ env.PROD_ENV }}" --version-label "${{ steps.prev.outputs.prev }}"
          exit 1
