name: OIDC - Echo claims
on: { workflow_dispatch: {} }
permissions: { id-token: write, contents: read }
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Get ID token
        id: tok
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            core.setOutput('token', token);
      - name: Print claims
        run: |
          python - <<'PY'
          import os, json, base64
          t=os.environ['TOKEN']
          payload=t.split('.')[1] + '=='
          print(json.dumps(json.loads(base64.urlsafe_b64decode(payload)), indent=2))
          PY
        env:
          TOKEN: ${{ steps.tok.outputs.token }}
