name: Rcvo – OIDC Ops Toolbox
on:
  workflow_dispatch:
    inputs:
      target:
        description: "UI ou API ?"
        required: true
        type: choice
        options: [UI, API]
      action:
        description: "Action"
        required: true
        type: choice
        options: [health, restart, fetch-eb-logs]
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Exécuter
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ inputs.target }}" = "UI" ]; then
            ENV="Rcvo-UI-prod"
          else
            ENV="Rcvo-Backend-prod"
          fi

          case "${{ inputs.action }}" in
            health)
              URL="http://$(aws elasticbeanstalk describe-environments --environment-names "$ENV" --query 'Environments[0].EndpointURL' --output text)/health"
              code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
              echo "Health: $URL -> $code"; test "$code" = "200"
              ;;
            restart)
              aws elasticbeanstalk restart-app-server --environment-name "$ENV"
              echo "Restart demandé."
              ;;
            fetch-eb-logs)
              aws elasticbeanstalk request-environment-info --environment-name "$ENV" --info-type tail
              sleep 15
              URL=$(aws elasticbeanstalk retrieve-environment-info --environment-name "$ENV" --info-type tail --query 'EnvironmentInfo[-1].Message' --output text)
              curl -fSL "$URL" -o eb-logs.zip
              echo "Logs EB téléchargés: eb-logs.zip (artefact)"
              ;;
          esac
      - name: Upload artefact (si présent)
        if: inputs.action == 'fetch-eb-logs'
        uses: actions/upload-artifact@v4
        with:
          name: eb-logs
          path: eb-logs.zip
